apiVersion: v1
description: A Helm chart for the Hetzner DNS webhook for cert-manager
name: cert-manager-webhook-hetzner
version: 0.1.0
appVersion: 0.1.0
maintainers:
  - name: mecodia GmbH
    url: https://github.com/mecodia/cert-manager-webhook-hetzner